# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         CGI-Auth-Auto
version:      1.004
version_from: lib/CGI/Auth/Auto.pm
installdirs:  site
requires:
    CGI::Auth:                     0
    HTML::Template:                0

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.17
