# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         CGI-Auth-Auto
version:      1.12
version_from: lib/CGI/Auth/Auto.pm
installdirs:  site
requires:
    Carp:                          0
    CGI::Auth:                     0
    Data::Dumper:                  0
    HTML::Template:                0
    HTML::Template::Default:       0
    LEOCHARRE::DEBUG:              1.06

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.30
